# Generated by Django 4.0.4 on 2022-07-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Mobile_Number', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
            ],
        ),
    ]
