# Generated by Django 4.0.4 on 2022-07-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('purchase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.purchase')),
                ('Address', models.CharField(max_length=500)),
                ('Pincode', models.IntegerField(max_length=6)),
            ],
            bases=('api.purchase',),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile_Number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='MRP',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Pricing',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Quantity',
            field=models.IntegerField(max_length=15),
        ),
    ]
